apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: joget
subjects:
- kind: ServiceAccount
  name: mysql-sa
  namespace: joget
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
